BC_PROJECT_NAME=CppProject
BC_VCPKG_PKGS=
BUILDCORE_PATH=deps/buildcore
include ${BUILDCORE_PATH}/base.mk

ifeq ($(BC_OS),darwin)
	PROJECT_EXECUTABLE=./build/${BC_CURRENT_BUILD}/${BC_PROJECT_NAME}.app/Contents/MacOS/${BC_PROJECT_NAME}
else
	PROJECT_EXECUTABLE=./build/${BC_CURRENT_BUILD}/bin/${BC_PROJECT_NAME}
endif

.PHONY: run
run: build
	${BC_ENVRUN} ${PROJECT_EXECUTABLE}
.PHONY: debug
debug: build
	${BC_ENVRUN} ${BC_DEBUGGER} ${PROJECT_EXECUTABLE}
