BC_VAR_PROJECT_NAME=CppProject
BC_VAR_VCPKG_PKGS=
BUILDCORE_PATH=deps/buildcore
include ${BUILDCORE_PATH}/base.mk

ifeq ($(BC_VAR_OS),darwin)
	PROJECT_EXECUTABLE=./build/${BC_VAR_CURRENT_BUILD}/${BC_VAR_PROJECT_NAME}.app/Contents/MacOS/${BC_VAR_PROJECT_NAME}
else
	PROJECT_EXECUTABLE=./build/${BC_VAR_CURRENT_BUILD}/bin/${BC_VAR_PROJECT_NAME}
endif

.PHONY: run
run: build
	${BC_ENVRUN} ${PROJECT_EXECUTABLE}
.PHONY: debug
debug: build
	${BC_DEBUGGER} ${PROJECT_EXECUTABLE}
